# Generated by Django 5.1.3 on 2024-12-01 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='data_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
